### ISSUE TITLE
Actividades sostenibles dirigida a principiantes

### ISSUE THREAD

**Issue by javlc** [BoliviaJS/Organizacion#1]
Creo que para que la comunidad tenga un atractivo a la comunidad en general, uno de los enfoques que veo útil  es impartir conocimiento sobre Javascript para principiantes mediante materiales o técnicas de enseñanza prácticos.

Este material tiene que tocar temas importantes desde el principio pero fácilmente asimilable respecto al correcto uso de los distintas peculiaridades que tiene el lenguaje como por ej. "prototyping", diferencia con los lenguajes de programación que se denominan "strongly typed", cuáles son las pautas que permiten compensar la aparente inexistencia de "namespaces" o "classes", fortalezas del lenguaje, las cosas que se deben evitar, el uso correcto de patrones de diseño que mejor se adecúan para javascript, et cetera.

Este conocimiento tiene que ser sencillo, fácil de asimilar por un principiante, y que le abra la puerta para continuar el camino por cuenta propia, que despierte su curiosidad por conocer más.

Podrían realizarse en forma de "workshops", uno en cada evento, proporcionando material puntual de estudio, proporcionando ejercicios de programación, etc.

De este modo se puede atraer a nuevos participantes que recién empíezan con desarrollo, como también la motivación para que colegas profesionales en otras tecnologías también puedan hacer el salto hacia javascript.

**Comment by dev123dev123** [comment]
Concuerdo contigo Javier es importante empezar a tener workshops, presentaciones, etc desde el punto de vista de personas que se estan iniciando, pero hacerlo de una forma muy practica ya que la mayoria a lo que vi, son personas que ya usaron otro lenguaje, entonces el enfoque seria hacerlo mas practico.

**Comment by javlc** [comment]
Es cierto Wilson, en presentaciones como esta es todo un desafío poder realizar un workshop que llegue a todos los estratos de conocimiento que puedan tener los participantes.
Tu enfoque me parece adecuado.

**Comment by chitopolo** [comment]
Concuerdo con ustedes, trabajemos por ello!

**Comment by Carscv** [comment]
Cuenten conmigo xd
