### ISSUE TITLE
Slack team

### ISSUE THREAD

**Issue by dev123dev123** [BoliviaJS/Organizacion#2]
Guys,

He creado el team llamado boliviajs en slack, los que puedan registrarse haganlo.

**Comment by javlc** [comment]
Excelente.
Estoy esperando la invitación del administrador del team para poder usarlo.
javierglc@outlook.com

**Comment by carlitux** [comment]
@wilsonbalderrama alguna forma de hacer una autoinvitación? o van a agregar a mano?

**Comment by dev123dev123** [comment]
Ahora deberian poder registrarse sin permisos, pueden probarlo porfa?

**Comment by carlitux** [comment]
@wilsonbalderrama no, que tal algo así como los de http://latamjs.org/?

**Comment by dev123dev123** [comment]
ahh! ya entendi sorry, creo que debemos hacerlo asi.

**Comment by carlitux** [comment]
@wilsonbalderrama por cierto el no, es a que no funciona por lo menos a mi no me llego nada jejejeje. podríamos integrarlo en la pagina.

**Comment by dev123dev123** [comment]
cual es el dominio de tu correo?

**Comment by carlitux** [comment]
prove con el de gmail

**Comment by dev123dev123** [comment]
no tengo ninguna pending invitation o algo asi, maniana lo reviso @carlitux
